### ISSUE TITLE
建议：分页居中

### ISSUE THREAD

**Issue by rankment** [Licoy/wordpress-theme-puock#186]
- 是否为已有功能：是
- 建议阐述：分页居中

目前可以在主题设置中通过全局CSS增加如下代码实现：

```css
.p-flex-s-right {
  display: flex;
  justify-content: flex-end;
  align-items: center;
}
```

效果：

![image](https://user-images.githubusercontent.com/113095229/193408242-5b4d4413-8655-4875-a042-187b3b3ee20f.png)
