### ISSUE TITLE
「关于博主」小组件中的美化

### ISSUE THREAD

**Issue by Wenutu** [Licoy/wordpress-theme-puock#252]
- 是否为已有功能：是
- 建议阐述：变为三栏 文章数、阅读量、评论数
```html
<div class="mt10 author_count"> 
	<ul>                   
		<li><span>文章数</span><strong>2</strong></li>
		<li><span>浏览量</span><strong>95</strong></li>                    
		<li><span>评论数</span><strong>1</strong></li>
	</ul>
</div>
```
对应css我是在额外css中添加的，想提Pull requests，应该在style.js修改，压缩为style.min.js，如果您觉得这个美化可用，那么可以加入源代码中
```css
.author_count ul {display:-moz-flex;display:-ms-flex;display:-o-flex;display:flex;text-align:center;margin-left:0;}
.author_count ul li {float:left;list-style:none;width:33.333%;border-right:1px #5c5f62 solid;padding:8px 0;font-weight:300;}
.author_count ul li:last-child {border-right:1px solid transparent;}
.author_count ul li span {display:block;font-size:14px;color:#999;}
.author_count ul li strong {font-weight:bold;}

```
最后是这样
<img width="436" alt="image" src="https://user-images.githubusercontent.com/80742588/212965892-14b6aada-4a22-4e1c-8170-f8e38727a8e2.png">
