### ISSUE TITLE
几处小建议

### ISSUE THREAD

**Issue by totoropcbeta** [Licoy/wordpress-theme-puock#28]
- 增加数学公式显示
> 引用MathJaxV3，放在footer.php开始处

```html
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
<script>
MathJax = {
  tex: {
      inlineMath: [['<span class="katex-eq" data-katex-display="false">', '</span>'], ['\\(', '\\)']],
      inlineMath: [['$', '$'], ['\\(', '\\)']],
      displayMath: [['[Latex]', '[/Latex]'], ['$$', '$$'], ['\\[', '\\]']]
  }
};
</script>
```

- 添加引用块显示
> 添加在主题根目录/assets/css/style.css

白昼模式
```css
blockquote{padding-left: 1em;margin: 1em 0em 1em 0;font-weight: 400;border-left: 4px solid rgba(0, 0, 0, .12);background-color:#f8f8f9}
```
黑暗模式
```css
.puock-dark blockquote{border-color: rgba(255, 255, 255, .2);background-color:#2f3840}
```
- 一言侧边栏小工具
> 添加自定义HTML

html代码如下，代码出处[一言](https://developer.hitokoto.cn/sentence/demo/#%E7%BD%91%E9%A1%B5)
```html
<p id="hitokoto"><a href="#" id="hitokoto_text">:D 获取中...</a></p>
<script>
  fetch('https://v1.hitokoto.cn')
    .then(response => response.json())
    .then(data => {
      const hitokoto = document.getElementById('hitokoto_text')
      hitokoto.href = 'https://hitokoto.cn/?uuid=' + data.uuid
      hitokoto.innerText = data.hitokoto
    })
    .catch(console.error)
</script>
```
