### ISSUE TITLE
如何关闭标题下划线

### ISSUE THREAD

**Issue by C63H88CoN14O14P** [Licoy/wordpress-theme-puock#329]
作者您好,我似乎并没有找到如何关闭标题中蓝色下滑线的选项,如果可以,请告诉我如何设置
情况,我的编辑视图如下
![image](https://github.com/Licoy/wordpress-theme-puock/assets/95567275/4687ee7c-0951-49a9-b38d-4486494da5ea)
但是实际上的效果是这样的,非常不协调,所以我希望把下划线取消了
![image](https://github.com/Licoy/wordpress-theme-puock/assets/95567275/4cf51c5f-1d3b-4785-9825-2defc09d9561)

**Comment by hausen1012** [comment]
试试加入css。
```css
#post .entry-content h1:after, #page .entry-content h1:after, .block-content .entry-content h1:after, #post .entry-content-box h1:after, #page .entry-content-box h1:after, .block-content .entry-content-box h1:after, #post .entry-content h2:after, #page .entry-content h2:after, .block-content .entry-content h2:after, #post .entry-content-box h2:after, #page .entry-content-box h2:after, .block-content .entry-content-box h2:after, #post .entry-content h3:after, #page .entry-content h3:after, .block-content .entry-content h3:after, #post .entry-content-box h3:after, #page .entry-content-box h3:after, .block-content .entry-content-box h3:after, #post .entry-content h4:after, #page .entry-content h4:after, .block-content .entry-content h4:after, #post .entry-content-box h4:after, #page .entry-content-box h4:after, .block-content .entry-content-box h4:after, #post .entry-content h5:after, #page .entry-content h5:after, .block-content .entry-content h5:after, #post .entry-content-box h5:after, #page .entry-content-box h5:after, .block-content .entry-content-box h5:after, #post .entry-content h6:after, #page .entry-content h6:after, .block-content .entry-content h6:after, #post .entry-content-box h6:after, #page .entry-content-box h6:after, .block-content .entry-content-box h6:after {
    display:none;
}
```
