### ISSUE TITLE
请问一下主页的缩略图显示大小或者比例可以修改吗

### ISSUE THREAD

**Issue by vbskycn** [Licoy/wordpress-theme-puock#367]
请教一下如何修改显示的比例，或者说裁剪的大小，因为我的图片都是800×538的，现在的比例看起来有点不协调，请问一下如何修改这个裁剪比例或者是说显示的比例

**Comment by Lvshujun0918** [comment]
在主题的自定义样式代码里加入这几行即可，自行修改其中的宽和高
```css
.pk-widget img {
    max-width: 100%;
    height: 80px;
    object-fit: cover;
    width: 120px;
}
.thumbnail img {
    width: 200px;
    height: 100px !important;
    object-fit: cover;
}
```
