### ISSUE TITLE
关于英文换行的一些想法

### ISSUE THREAD

**Issue by Tyler913** [Licoy/wordpress-theme-puock#416]
目前来说如果英文长度超出了一行的限制，他不会连带着整个单词都换行，他只会把多出来的几个字母进行换行处理

讲实话，这个又带你影响阅读体验，作者大大是否可以像微信啊，word等软件一样。在行数不够的时候连带着整个单词一起换行，而不是把单词拆分开来换行

<img width="801" alt="image" src="https://github.com/Licoy/wordpress-theme-puock/assets/74124552/6033116f-76ea-4fcd-ad38-bfcb31de2920">

**Comment by Lvshujun0918** [comment]
你可以在主题的设置页面的**脚本及样式**的**头部自定义全局CSS样式**加入如下代码
```css
body p {
    word-break: break-word;
}
```
